### ISSUE TITLE
Shorten base URL of PlanSys2 website

### ISSUE THREAD

**Issue by ralph-lange** [PlanSys2/PlanSys2.github.io#10]
I've opened a [PR](https://github.com/ros2/ros2_documentation/pull/2843) to add the PlanSys2 website to docs.ros.org.

In doing so, I noticed that the URL of the website can easily be shortened by renaming this repo to `PlanSys2.github.io`. The part before `.github.io` has to be identical with the organization name. Then, the documentation should be reachable directly under https://plansys2.github.io/.

**Comment by fmrico** [comment]
Hi @ralph-lange 

I have just renamed it to PlanSys2.github.io

Thanks for the tip!!

**Comment by ralph-lange** [comment]
Perfect. I've updated https://github.com/ros2/ros2_documentation/pull/2843 with the new, short url correspondingly.
